version: '3'
services:
  sass-3.4.2:
    build: ./3.4.2
    volumes:
      - ./${FILE:-scss/test.scss}:/usr/src/app/test.scss
  dart-sass-1.30.0:
    build: ./dart-sass-1.30.0
    volumes:
      - ./${FILE:-scss/test.scss}:/usr/src/app/test.scss
    depends_on:
      - sass-3.4.2
